#!/usr/bin/env python3
"""
comps.py — the URA comps engine behind the Eric Chiew property analysis skill.

Reads the local URA transaction dataset (ura_data.js, generated by fetch_ura_data.py)
and returns the comparable transactions needed to value a subject listing.

Usage
-----
    python comps.py --project "Grand Dunman" --size 1119 --price 2650000 --bedrooms 3
    python comps.py --project "Treasure At Tampines" --bedrooms 3 --months 12
    python comps.py --district D15 --bedrooms 3 --size 1100 --months 12
    python comps.py --list-projects "dunman"

Output is JSON on stdout: four comp tiers plus project vitals.
Add --table for a human-readable summary instead.
"""

import argparse
import json
import os
import statistics
import sys
from collections import Counter, defaultdict
from datetime import date
from difflib import get_close_matches

SQFT_PER_SQM = 10.7639

# Known dataset locations, relative to the repo root. The newest one wins — the browser
# app picks the same way, so both always read the same file.
DATA_CANDIDATES = [
    "FetchURA/ura_data.js",
    "property-analyzer/ura_data.js",
    "Netlify upload_property/ura_data.js",
    "House/ura_data.js",
    "ura_data.js",
]

ELITE_PRIMARIES = [
    "Nanyang Primary", "Henry Park Primary", "CHIJ St. Nicholas Girls'",
    "Raffles Girls' Primary", "Ai Tong", "Kong Hwa", "Rulang Primary",
    "Anglo-Chinese School (Primary)", "Tao Nan", "Catholic High",
    "Nan Hua Primary", "Pei Hwa Presbyterian", "Temasek Primary",
    "St. Hilda's Primary", "Methodist Girls' School (Primary)",
]


# ─────────────────────────────────────────────────────────────
#  Dataset loading
# ─────────────────────────────────────────────────────────────

def repo_root():
    """Walk up from this file to the repo root (three levels up from scripts/)."""
    here = os.path.abspath(os.path.dirname(__file__))
    return os.path.abspath(os.path.join(here, "..", "..", "..", ".."))


def find_data_file(explicit=None):
    if explicit:
        if not os.path.exists(explicit):
            sys.exit(f"Data file not found: {explicit}")
        return explicit
    root = repo_root()
    found = [(os.path.getmtime(p), p)
             for p in (os.path.join(root, rel) for rel in DATA_CANDIDATES)
             if os.path.exists(p)]
    if found:
        return max(found)[1]
    sys.exit(
        "No ura_data.js found. Generate one with:\n"
        "  python fetch_ura_data.py\n"
        "or pass --data <path>."
    )


def load_dataset(path):
    """Load ura_data.js in either the plain or the dictionary-encoded (compact) format.

    Returns (rows_as_dicts, meta) where every row has decoded string values.
    """
    with open(path, encoding="utf-8") as fh:
        raw = fh.read()
    start = raw.index("{")
    end = raw.rindex("}") + 1
    blob = json.loads(raw[start:end])

    cols = blob["cols"]
    meta = blob.get("meta") or {}
    idx = {c: i for i, c in enumerate(cols)}
    rows = []

    for r in blob["rows"]:
        rec = {}
        for col, i in idx.items():
            val = r[i]
            dic = meta.get(col)
            # Compact format stores an integer index into meta[col]
            if dic and isinstance(val, int) and 0 <= val < len(dic):
                val = dic[val]
            rec[col] = val
        rows.append(rec)

    header = raw.split("\n", 1)[0].strip().lstrip("/").strip()
    return rows, {"file": path, "header": header, "count": len(rows)}


# ─────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────

def bedroom_from_sqft(sqft):
    if sqft <= 430:
        return "Studio"
    if sqft <= 650:
        return "1-Bedroom"
    if sqft <= 970:
        return "2-Bedroom"
    if sqft <= 1300:
        return "3-Bedroom"
    if sqft <= 2000:
        return "4-Bedroom"
    if sqft <= 2800:
        return "5-Bedroom"
    return "Penthouse"


def months_ago(row, cutoff_year, cutoff_month):
    return (row["year"], row["month"]) >= (cutoff_year, cutoff_month)


def cutoff(months):
    today = date.today()
    total = today.year * 12 + (today.month - 1) - months
    return total // 12, (total % 12) + 1


def summarise(rows, label):
    """Median-centred summary of a comp set."""
    if not rows:
        return {"label": label, "n": 0}
    psfs = sorted(r["psf"] for r in rows)
    prices = sorted(r["transactionValue"] for r in rows)
    sizes = sorted(r["size"] for r in rows)
    dates = sorted((r["year"], r["month"]) for r in rows)
    return {
        "label": label,
        "n": len(rows),
        "psf_median": round(statistics.median(psfs)),
        "psf_p25": round(psfs[max(0, int(len(psfs) * 0.25) - 0)]),
        "psf_p75": round(psfs[min(len(psfs) - 1, int(len(psfs) * 0.75))]),
        "psf_min": psfs[0],
        "psf_max": psfs[-1],
        "price_median": round(statistics.median(prices)),
        "size_median": round(statistics.median(sizes)),
        "date_from": f"{dates[0][0]}-{dates[0][1]:02d}",
        "date_to": f"{dates[-1][0]}-{dates[-1][1]:02d}",
        "projects": [p for p, _ in Counter(r["project"] for r in rows).most_common(8)],
    }


def as_transactions(rows, limit=25):
    """The actual prints, newest first — these go into the report table."""
    ordered = sorted(rows, key=lambda r: (r["year"], r["month"]), reverse=True)[:limit]
    return [
        {
            "project": r["project"],
            "date": f"{r['year']}-{r['month']:02d}",
            "size": r["size"],
            "psf": r["psf"],
            "price": r["transactionValue"],
            "floor": r["floorRange"],
            "bedroom": r["bedroomType"],
            "saleType": r["saleType"],
            "district": r["district"],
            "tenure": r.get("tenure"),
        }
        for r in ordered
    ]


def cagr(series):
    """series: {year: median_psf}. Returns compound annual growth over the span."""
    years = sorted(series)
    if len(years) < 2:
        return None
    first, last = years[0], years[-1]
    span = last - first
    if span <= 0 or series[first] <= 0:
        return None
    return round(((series[last] / series[first]) ** (1 / span) - 1) * 100, 2)


def yearly_median_psf(rows):
    buckets = defaultdict(list)
    for r in rows:
        buckets[r["year"]].append(r["psf"])
    return {y: round(statistics.median(v)) for y, v in sorted(buckets.items())}


# ─────────────────────────────────────────────────────────────
#  Main analysis
# ─────────────────────────────────────────────────────────────

def resolve_project(rows, name):
    """Fuzzy-match a listing's project name to a URA project name."""
    if not name:
        return None, []
    names = sorted({r["project"] for r in rows})
    upper = {n.upper(): n for n in names}
    want = name.strip().upper()

    if want in upper:
        return upper[want], []
    contains = [n for u, n in upper.items() if want in u or u in want]
    if len(contains) == 1:
        return contains[0], []
    close = get_close_matches(want, list(upper), n=6, cutoff=0.6)
    suggestions = sorted({upper[c] for c in close} | set(contains))
    if len(suggestions) == 1:
        return suggestions[0], []
    return None, suggestions


def build(args):
    rows, dsmeta = load_dataset(find_data_file(args.data))

    if args.list_projects:
        needle = args.list_projects.upper()
        hits = sorted({r["project"] for r in rows if needle in r["project"].upper()})
        return {"query": args.list_projects, "matches": hits}

    project, suggestions = resolve_project(rows, args.project)
    if args.project and not project:
        return {
            "error": f"Project '{args.project}' not found in the URA dataset.",
            "suggestions": suggestions,
            "hint": "Use --list-projects <substring> to search, or drop --project to run district comps only.",
        }

    proj_rows = [r for r in rows if r["project"] == project] if project else []

    # Fill in what the listing did not state, from the project's own record.
    district = args.district or (Counter(r["district"] for r in proj_rows).most_common(1)[0][0] if proj_rows else None)
    segment = args.segment or (Counter(r["marketSegment"] for r in proj_rows).most_common(1)[0][0] if proj_rows else None)
    size = args.size
    if size is None and args.price and args.psf:
        size = round(args.price / args.psf)
    bedroom = None
    if args.bedrooms:
        bedroom = {1: "1-Bedroom", 2: "2-Bedroom", 3: "3-Bedroom",
                   4: "4-Bedroom", 5: "5-Bedroom"}.get(args.bedrooms)
    elif size:
        bedroom = bedroom_from_sqft(size)

    psf = args.psf
    if psf is None and args.price and size:
        psf = round(args.price / size)

    cy, cm = cutoff(args.months)
    recent = [r for r in rows if months_ago(r, cy, cm)]

    def size_ok(r):
        if not size or args.size_tolerance <= 0:
            return True
        lo = size * (1 - args.size_tolerance)
        hi = size * (1 + args.size_tolerance)
        return lo <= r["size"] <= hi

    def bed_ok(r):
        return bedroom is None or r["bedroomType"] == bedroom

    # ── Tier 1: same project ────────────────────────────────
    t1 = [r for r in recent if r["project"] == project and bed_ok(r) and size_ok(r)] if project else []
    if project and len(t1) < 3:
        # Relax the size band before giving up on the strongest comp tier.
        t1 = [r for r in recent if r["project"] == project and bed_ok(r)]

    # ── Tier 2: same district + bedroom ─────────────────────
    t2 = [r for r in recent
          if district and r["district"] == district and bed_ok(r) and size_ok(r)
          and r["project"] != project]

    # ── Tier 3: same segment + bedroom ──────────────────────
    t3 = [r for r in recent
          if segment and r["marketSegment"] == segment and bed_ok(r) and size_ok(r)
          and r["project"] != project]

    # ── Tier 4: named benchmark projects ────────────────────
    t4 = []
    benchmarks = {}
    for bname in (args.benchmark or []):
        bproj, bsug = resolve_project(rows, bname)
        if not bproj:
            benchmarks[bname] = {"error": "not found", "suggestions": bsug}
            continue
        brows = [r for r in recent if r["project"] == bproj and bed_ok(r)]
        if len(brows) < 3:
            brows = [r for r in rows if r["project"] == bproj and bed_ok(r)]
        t4 += brows
        all_b = [r for r in rows if r["project"] == bproj]
        benchmarks[bproj] = {
            **summarise(brows, f"benchmark: {bproj}"),
            "district": Counter(r["district"] for r in all_b).most_common(1)[0][0],
            "segment": Counter(r["marketSegment"] for r in all_b).most_common(1)[0][0],
            "tenure": Counter(r["tenure"] for r in all_b).most_common(1)[0][0],
            "psf_by_year": yearly_median_psf(all_b),
            "transactions": as_transactions(brows, 10),
        }

    # ── Project vitals ──────────────────────────────────────
    vitals = None
    if project:
        v24y, v24m = cutoff(24)
        last24 = [r for r in proj_rows if months_ago(r, v24y, v24m)]
        by_year = yearly_median_psf(proj_rows)
        dist_rows = [r for r in rows if r["district"] == district]
        dist_by_year = yearly_median_psf(dist_rows)
        vitals = {
            "project": project,
            "district": district,
            "segment": segment,
            "tenure": Counter(r["tenure"] for r in proj_rows).most_common(1)[0][0],
            "propertyType": Counter(r["propertyType"] for r in proj_rows).most_common(1)[0][0],
            "total_transactions": len(proj_rows),
            "transactions_last_24m": len(last24),
            "velocity_verdict": (
                "strong" if len(last24) >= 40 else
                "healthy" if len(last24) >= 15 else
                "thin" if len(last24) >= 5 else
                "very thin" if len(last24) >= 1 else
                "frozen — zero prints in 24 months"
            ),
            "sale_type_mix": dict(Counter(r["saleType"] for r in proj_rows)),
            "bedroom_mix": dict(Counter(r["bedroomType"] for r in proj_rows).most_common()),
            "psf_by_year": by_year,
            "psf_cagr_pct": cagr(by_year),
            "district_psf_by_year": dist_by_year,
            "district_psf_cagr_pct": cagr(dist_by_year),
            "size_range": [min(r["size"] for r in proj_rows), max(r["size"] for r in proj_rows)],
            "first_seen": min(f"{r['year']}-{r['month']:02d}" for r in proj_rows),
        }
        c1, c2 = vitals["psf_cagr_pct"], vitals["district_psf_cagr_pct"]
        vitals["vs_district"] = (
            None if c1 is None or c2 is None else
            "outperforming" if c1 > c2 + 0.5 else
            "underperforming" if c1 < c2 - 0.5 else
            "in line"
        )

    # ── District percentile context for the asking PSF ──────
    percentile = None
    if psf and t2:
        band = sorted(r["psf"] for r in t2)
        below = sum(1 for p in band if p < psf)
        percentile = round(below / len(band) * 100)

    out = {
        "dataset": dsmeta,
        "subject": {
            "project": project or args.project,
            "district": district,
            "segment": segment,
            "size_sqft": size,
            "price": args.price,
            "psf": psf,
            "bedroom_type": bedroom,
            "comp_window_months": args.months,
            "size_tolerance_pct": round(args.size_tolerance * 100),
        },
        "asking_psf_percentile_in_district_comps": percentile,
        "tiers": {
            "tier1_same_project": {**summarise(t1, f"same project: {project}"),
                                   "transactions": as_transactions(t1)},
            "tier2_same_district": {**summarise(t2, f"same district {district} + {bedroom}"),
                                    "transactions": as_transactions(t2, 15)},
            "tier3_same_segment": {**summarise(t3, f"same segment {segment} + {bedroom}"),
                                   "transactions": as_transactions(t3, 10)},
        },
        "benchmarks": benchmarks,
        "project_vitals": vitals,
        "recommended_tier": (
            "tier1_same_project" if len(t1) >= 3 else
            "tier2_same_district" if len(t2) >= 5 else
            "tier3_same_segment"
        ),
        "notes": [],
    }

    if project and len(t1) < 3:
        out["notes"].append(
            f"Only {len(t1)} in-project prints in the last {args.months} months — thin liquidity "
            "is itself an exit-strategy penalty (Eric's volume rule)."
        )
    if vitals and vitals["transactions_last_24m"] == 0:
        out["notes"].append(
            "Zero transactions in 24 months. This is the Lilium problem: no matching prints means "
            "no valuation support and no exit."
        )
    if psf and segment == "OCR" and psf > 2500:
        out["notes"].append(
            f"Asking ${psf:,} psf in the OCR is above Eric's $2,500 psf threshold — 'disgusting', "
            "no room left for appreciation."
        )
    return out


def render_table(res):
    if "error" in res:
        print(res["error"])
        if res.get("suggestions"):
            print("Did you mean: " + ", ".join(res["suggestions"]))
        return
    if "matches" in res:
        print(f"{len(res['matches'])} project(s) matching '{res['query']}':")
        for m in res["matches"]:
            print("  " + m)
        return

    s = res["subject"]
    print(f"\nSUBJECT  {s['project']}  |  {s['district']} {s['segment']}  |  "
          f"{s['bedroom_type']}  {s['size_sqft']} sqft")
    if s["psf"]:
        print(f"         asking ${s['price']:,} = ${s['psf']:,} psf")
    if res.get("asking_psf_percentile_in_district_comps") is not None:
        print(f"         sits at the {res['asking_psf_percentile_in_district_comps']}th percentile "
              f"of district comps")

    v = res.get("project_vitals")
    if v:
        print(f"\nVITALS   {v['total_transactions']} prints total, {v['transactions_last_24m']} in 24m "
              f"({v['velocity_verdict']})")
        print(f"         tenure {v['tenure']} | {v['propertyType']}")
        print(f"         PSF by year {v['psf_by_year']}")
        print(f"         CAGR {v['psf_cagr_pct']}% vs district {v['district_psf_cagr_pct']}% "
              f"-> {v['vs_district']}")

    for key, tier in res["tiers"].items():
        if not tier.get("n"):
            print(f"\n{key}: no comps")
            continue
        star = " <== recommended" if key == res["recommended_tier"] else ""
        print(f"\n{tier['label']}  (n={tier['n']}, {tier['date_from']} to {tier['date_to']}){star}")
        print(f"  median ${tier['psf_median']:,} psf   p25 ${tier['psf_p25']:,}  p75 ${tier['psf_p75']:,}"
              f"   median price ${tier['price_median']:,}")
        for t in tier["transactions"][:8]:
            print(f"    {t['date']}  {t['project'][:28]:<28} {t['size']:>5} sqft  "
                  f"${t['psf']:>5,} psf  ${t['price']:>10,}  {t['floor']:<6} {t['saleType']}")

    for b, data in (res.get("benchmarks") or {}).items():
        if data.get("error"):
            print(f"\nBENCHMARK {b}: {data['error']}")
            continue
        print(f"\nBENCHMARK {b}  (n={data['n']})  median ${data.get('psf_median', 0):,} psf   "
              f"{data['district']} {data['segment']} {data['tenure']}")
        print(f"  PSF by year {data['psf_by_year']}")

    for n in res.get("notes", []):
        print(f"\n! {n}")
    print()


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--project", help="Project name from the listing (fuzzy matched)")
    p.add_argument("--district", help="e.g. D15")
    p.add_argument("--segment", choices=["CCR", "RCR", "OCR"])
    p.add_argument("--size", type=float, help="Floor area in sqft")
    p.add_argument("--price", type=float, help="Asking price in SGD")
    p.add_argument("--psf", type=float, help="Asking PSF (derived from price/size if omitted)")
    p.add_argument("--bedrooms", type=int, help="Bedroom count (inferred from size if omitted)")
    p.add_argument("--months", type=int, default=12, help="Comp window in months (default 12)")
    p.add_argument("--size-tolerance", type=float, default=0.15,
                   help="Size band as a fraction, default 0.15 = +/-15%%")
    p.add_argument("--benchmark", action="append",
                   help="Named benchmark project, repeatable (the Treasure/Costa Del Sol pattern)")
    p.add_argument("--list-projects", help="List dataset project names containing this substring")
    p.add_argument("--data", help="Path to ura_data.js")
    p.add_argument("--table", action="store_true", help="Human-readable output instead of JSON")
    args = p.parse_args()

    res = build(args)
    if args.table:
        render_table(res)
    else:
        json.dump(res, sys.stdout, indent=2, default=str)
        print()


if __name__ == "__main__":
    main()
